version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-database
    user: "1000:1000" # Adiciona permissão do usuário
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance-ai
    ports:
      - 5432:5432
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.postgres_data
